### ISSUE TITLE
Autorotate

### ISSUE THREAD

**Issue by mythodeia** [leverdeterre/JMActionSheetDescription#1]
thanks for the excellent library! 
I only have one issue with the rotation. 
If you rotate the demo the dimming view does not expand to fill the screen when testing in iPhone & the actionsheetpicker is not visible anymore. This happens when you open the picker in portrait and then rotate to landscape.
thanks for your time

**Comment by leverdeterre** [comment]
Hi,
Thanks for tour report, i have notice that when I had the support of iOS9 splitViews. I'm going to fix this by implementing layout using manual frame computing :)

**Comment by mythodeia** [comment]
:+1: you can close this when ready then
thanks again

**Comment by leverdeterre** [comment]
Fix on 0.4.6
